import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../styles/main.css";
import Footer from "@/components/templates/Footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <link rel="icon" href="/svg/find-a-helpline-brandmark.svg" />
      <body className="font-sans">{children}</body>
      <Footer />
    </html>
  );
}
